### ISSUE TITLE
프로젝트 API를 구현합니다.

### ISSUE THREAD

**Issue by 213kky** [devridge-team-project/devridge-server#118]
## Description 📝
* 프로젝트 API를 구현합니다.

## TODO ✅
- [x] 댓글 CRUD 추가
- [x] 댓글 추천/비추천 기능 추가
- [x] 스크랩 기능 추가
- [x] 게시글 추천/비추천 기능 추가
