### ISSUE TITLE
좋아요 수 증감에 대해 분산락을 적용합니다.

### ISSUE THREAD

**Issue by yu-heejin** [devridge-team-project/devridge-server#128]
## Description 📝
* 좋아요 수에 대한 분산락을 적용합니다.

## TODO ✅
- [ ] Redis 연결하기
- [ ] 분산락 코드 작성하기
- [ ] EC2에 redis 설치하기
- [ ] 테스트 코드 작성하기
- [ ] E2E 테스트 해보기
