### ISSUE TITLE
커뮤니티 API의 전반적인 코드 리팩토링을 진행합니다.

### ISSUE THREAD

**Issue by 213kky** [devridge-team-project/devridge-server#135]
## Description 📝
* 자유게시판 상세 조회와 자유게시판 게시글 목록 조회의 hashtag 부분에서 결과가 없을 시 빈 배열을 반환하도록 통일합니다.
* 프로젝트의 roles 부분을 리스트로 처리하도록 수정합니다.
* 스터디 부분의 데이터 전체 인원과 현재 인원을 삭제합니다.
* 스터디 상세 조회의 위치정보 반환값이 정상적으로 반환되지않는 오류를 수정합니다.
* 스터디 상세 조회에서 카테고리 값을 반환하지 않는 오류를 수정합니다.

## TODO ✅
- [x] 자유게시판 상세 조회와 자유게시판 게시글 목록의 hashtag의 반환 형태 통일
- [x] 프로젝트의 roles 부분을 리스트로 처리하도록 수정
- [x] 스터디 부분의 데이터 전체인원과 현재 인원을 삭제
- [x] 스터디 상세 조회의 위치정보 반환값이 정상적으로 반환되지않는 오류를 수정
- [x] 스터디 상세 조회에서 카테고리 값을 반환하지 않는 오류를 수정
