### ISSUE TITLE
서버 배포 오류 수정 및 GitHub Actions yml 설정 파일을 수정합니다.

### ISSUE THREAD

**Issue by yu-heejin** [devridge-team-project/devridge-server#141]
## Description 📝
* 서버 배포 오류 수정 및 GitHub Actions yml 설정 파일을 수정합니다.

## TODO ✅
- [x] 서버 배포 오류 수정
- [ ] dev-ci 파일 삭제
- [ ] 액션 타겟 수정
