### ISSUE TITLE
커뮤니티에 해당하는 게시글 상세조회 api의 응답dto에 scrap수와 comment수를 추가합니다.

### ISSUE THREAD

**Issue by 213kky** [devridge-team-project/devridge-server#145]
## Description 📝
* 자유게시글 상세조회 응답 dto에 scrap수와 comment수를 추가합니다.
* 프로젝트 상세조회 응답 dto에 scrap수와 comment수를 추가합니다.
* 스터디 상세조회 응답 dto에 scrap수와 comment수를 추가합니다.

## TODO ✅
- [x] 자유게시글 상세조회 응답 dto에 scrap수와 comment수를 추가
- [x] 프로젝트 상세조회 응답 dto에 scrap수와 comment수를 추가
- [x] 스터디 상세조회 응답 dto에 scrap수와 comment수를 추가
