### ISSUE TITLE
dev 배포 환경과 prod 배포 환경을 분리합니다.

### ISSUE THREAD

**Issue by yu-heejin** [devridge-team-project/devridge-server#48]
## Description 📝
* 개발 서버와 운영 서버를 분리합니다.

## TODO ✅
- [x] RDS 설정
- [x] EC2 설정
- [x] Dockerfile.prod 설정
- [x] VPC, 서브넷 설정
- [x] GitHub Actions 설정
- [x] application-prod.yml 설정
