### ISSUE TITLE
운영서버 환경을 보완 및 리팩토링합니다.

### ISSUE THREAD

**Issue by yu-heejin** [devridge-team-project/devridge-server#56]
## Description 📝
* 구축된 운영서버에 추가 환경을 보완 및 리팩토링을 진행합니다.

## TODO ✅
- [x] RDS 환경 설정 및 DDL 생성
- [x] https 인증서 발급 및 도메인 연결 @213kky 
- [x] EC2, RDS 연동
- [x] GitHub Actions Docker Cache 기능 #46
- [ ] 릴리즈, 태깅 자동화
