### ISSUE TITLE
무한스크롤 구현 및 화면 변경에 따른 Community API 수정 및 리팩토링합니다.

### ISSUE THREAD

**Issue by 213kky** [devridge-team-project/devridge-server#76]
## Description 📝
* 자유게시판 전체 목록 무한스크롤을 구현합니다.
* 자유게시글 댓글 목록 무한스크롤을 구현합니다.
* 프로젝트 전체 목록 무한스크롤을 구현합니다.
* 화면 디자인에 맞게 api를 수정합니다.

## TODO ✅
- [x] 자유게시판 전체 목록 무한스크롤 구현
- [x] 자유게시글 댓글 목록 무한스크롤 구현
- [x] 프로젝트 전체 목록 무한스크롤 구현
- [x] 화면 디자인에 맞게 api 수정
