### ISSUE TITLE
채팅방 목록 조회 시 응답 데이터를 수정합니다.

### ISSUE THREAD

**Issue by yu-heejin** [devridge-team-project/devridge-server#89]
## Description 📝
* 채팅방 목록 조회 시 응답 데이터를 수정합니다.

## TODO ✅
- [x] 채팅방 이름에 유저 정보 추가
- [x] 채팅방 조회 시 lastMessage 추가
- [x] 채팅 메세지, 채팅방 목록에 createdAt, updatedAt 추가
