### ISSUE TITLE
freeboard, study 오류 해결 및 study 무한스크롤을 구현합니다.

### ISSUE THREAD

**Issue by 213kky** [devridge-team-project/devridge-server#96]
## Description 📝
* freeboard 게시글 리스트에서 내용 부분이 누락된 것을 추가합니다.
* study 모집 글이 이미지 없이 작성 안되는 오류를 해결합니다.
* study 게시글 리스트 무한스크롤 구현합니다.

## TODO ✅
- [x] freeboard 게시글 리스트에서 내용 부분 추가
- [x] study 모집 글이 이미지 파일 없이 작성 안되는 오류를 해결
- [x] study 게시글 리스트 무한스크롤 구현
